language: node_js

matrix:
  fast_finish: true
  include:
    - os: windows
      dist: 1803-containers
    - os: linux
      dist: trusty
      sudo: required
      env:
        - CXX=g++-5
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - g++-5
            - libtommath0

node_js:
  - '12'
  - '11'
  - '10'
  - '8'
  - '6'

install:
  - if [[ "$TRAVIS_OS_NAME" != 'windows' ]]; then ./.ci/travis-install.sh; fi

script:
  - if [[ "$TRAVIS_OS_NAME" != 'windows' ]]; then sg firebird ./.ci/travis-build.sh; fi
  - if [[ "$TRAVIS_OS_NAME" = 'windows' ]]; then ./.ci/travis-build.sh; fi

cache:
  directories:
    - node_modules

git:
  depth: 1
