image:
  - Ubuntu1804
  - Visual Studio 2015

platform:
  - x64
  - x86

environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: true
  matrix:
    - nodejs_version: 6
    - nodejs_version: 8
    - nodejs_version: 9
    - nodejs_version: 10
    - nodejs_version: 11

shallow_clone: true

install:
  - ps: Install-Product node $env:nodejs_version $env:PLATFORM
  - cmd: if %PLATFORM% == "x64" call "C:\Program Files (x86)\Microsoft Visual Studio %MSVS_TOOLSET%.0\VC\vcvarsall.bat" amd64
  - cmd: if %PLATFORM% == "x86" call "C:\Program Files (x86)\Microsoft Visual Studio %MSVS_TOOLSET%.0\VC\vcvarsall.bat" x86
  - cmd: if "%PLATFORM%" == "x64" set FB_ZIP=Firebird-3.0.3.32900-0_x64.zip
  - cmd: if "%PLATFORM%" == "x86" set FB_ZIP=Firebird-3.0.3.32900-0_Win32.zip
  - ps: Start-FileDownload "https://github.com/FirebirdSQL/firebird/releases/download/R3_0_3/$env:FB_ZIP"
  - cmd: 7z x -oC:\Firebird %FB_ZIP%
  - cmd: set PATH=C:\Firebird;%PATH%
  - cmd: yarn --cache-folder=.yarn-cache
  - cmd: yarn bootstrap
  - cmd: yarn test
  - cmd: set ARTIFACTS_PATH=packages\node-firebird-native-api\build\Release
  - sh: sudo apt-get -y update
  - sh: sudo apt-get -y install libtommath
  - sh: wget -O Firebird-3.0.3.32900-0.amd64.tar.gz "https://github.com/FirebirdSQL/firebird/releases/download/R3_0_3/Firebird-3.0.3.32900-0.amd64.tar.gz"
  - sh: tar xzvf Firebird-3.0.3.32900-0.amd64.tar.gz
  - sh: (cd Firebird-3.0.3.32900-0.amd64; sudo ./install.sh -silent)
  - sh: sudo usermod -a -G firebird travis
  - sh: sg firebird -c "yarn --cache-folder=.yarn-cache"
  - sh: sg firebird -c "yarn bootstrap"
  - sh: sg firebird -c "yarn test"

cache:
  - .yarn-cache

artifacts:
  - path: $(ARTIFACTS_PATH)
    name: node-firebird-native-api
    type: zip

build: off
test: off
deploy: off
