name: Node CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-latest, windows-latest, macOS-latest]
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Firebird install (Linux)
      if: matrix.os == 'ubuntu-16.04'
      run: |
        sudo apt-get install libtommath0
        wget -O Firebird-3.0.3.32900-0.amd64.tar.gz "https://github.com/FirebirdSQL/firebird/releases/download/R3_0_3/Firebird-3.0.3.32900-0.amd64.tar.gz"
        tar xzvf Firebird-3.0.3.32900-0.amd64.tar.gz
        (cd Firebird-3.0.3.32900-0.amd64; sudo ./install.sh -silent)
        sudo usermod -a -G firebird `whoami`

    - name: Firebird install (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        set FB_ZIP=Firebird-3.0.3.32900-0_x64.zip
        powershell Invoke-WebRequest "https://github.com/FirebirdSQL/firebird/releases/download/R3_0_3/$env:FB_ZIP" -OutFile "$env:FB_ZIP"
        7z x -oC:\Firebird %FB_ZIP%
        set PATH=C:\Firebird;%PATH%
        set
        dir C:\Firebird

    - name: Build
      if: matrix.os != 'windows-latest'
      run: |
        yarn
        yarn bootstrap

    - name: Test (Linux)
      if: matrix.os == 'ubuntu-16.04'
      run: |
        sg firebird -c yarn test

    - name: Test (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        set PATH=C:\Firebird;%PATH%
        yarn
        yarn bootstrap
        yarn test
